# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-30 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emergency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=30, verbose_name='контакт')),
                ('phone', models.CharField(max_length=50, verbose_name='телефон')),
            ],
            options={
                'verbose_name_plural': 'экстренные телефоны',
                'verbose_name': 'экстренный телефон',
                'ordering': ['contact'],
            },
        ),
    ]
