# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-04 15:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='создан')),
                ('title', models.CharField(max_length=25, unique=True, verbose_name='название')),
                ('acronym', models.CharField(max_length=5, unique=True, verbose_name='кратко')),
                ('importance', models.IntegerField(default=0, verbose_name='(!)')),
                ('description', models.TextField(verbose_name='описание')),
                ('slug', models.SlugField(max_length=10, unique=True)),
                ('image', models.ImageField(upload_to='wiki/parts', verbose_name='Логотип')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='автор')),
            ],
            options={
                'verbose_name': 'раздел',
                'verbose_name_plural': 'разделы',
                'ordering': ['title'],
            },
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['title'], 'verbose_name': 'группу шаблона', 'verbose_name_plural': 'группы шаблонов'},
        ),
        migrations.AlterModelOptions(
            name='pattern',
            options={'ordering': ['ordnum'], 'verbose_name': 'секционный раздел в шаблоне', 'verbose_name_plural': 'шаблон статьи wiki'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['title'], 'verbose_name': 'секцию', 'verbose_name_plural': 'секции'},
        ),
        migrations.AlterField(
            model_name='group',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='создана'),
        ),
        migrations.AlterField(
            model_name='pattern',
            name='ordnum',
            field=models.IntegerField(verbose_name='№'),
        ),
        migrations.AlterField(
            model_name='pattern',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wiki.Section', verbose_name='секция'),
        ),
    ]
