# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-04 15:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_auto_20180904_1844'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='part',
            options={'ordering': ['importance', 'title'], 'verbose_name': 'раздел', 'verbose_name_plural': 'разделы'},
        ),
    ]
