# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-06 22:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0005_auto_20180906_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='ordnum',
            field=models.IntegerField(default='0', verbose_name='№'),
        ),
    ]
