# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-06 23:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0007_auto_20180907_0210'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='section',
            unique_together=set([]),
        ),
    ]
