# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-06 23:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0008_auto_20180907_0211'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='section',
            unique_together=set([('group', 'ordnum')]),
        ),
    ]
