# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-07 02:32
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0010_auto_20180907_0459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='acronym',
            field=models.CharField(max_length=10, unique=True, verbose_name='краткое'),
        ),
        migrations.AlterField(
            model_name='part',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, max_length=10, populate_from=['acronym'], unique=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='title',
            field=models.CharField(max_length=25, verbose_name='полное'),
        ),
    ]
