# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-07 16:34
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0011_auto_20180907_0532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='logo',
            field=models.ImageField(upload_to='wiki/part', verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='part',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, max_length=10, populate_from='acronym', unique=True),
        ),
    ]
