# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-07 16:49
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0012_auto_20180907_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique_with=('part',)),
        ),
    ]
