# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-08 22:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wiki', '0014_auto_20180909_0114'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='modified_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='modified_by', to=settings.AUTH_USER_MODEL, verbose_name='редактор'),
            preserve_default=False,
        ),
    ]
