# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-08 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0015_article_modified_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.IntegerField(choices=[('0', 'Черновик'), ('1', 'Опубликована'), ('2', 'Архив')], default=0, verbose_name='статус'),
        ),
    ]
