# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-08 22:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0016_auto_20180909_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.IntegerField(choices=[(0, 'Черновик'), (1, 'Опубликована'), (2, 'Архив')], default=0, verbose_name='статус'),
        ),
    ]
