# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-09 00:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0019_auto_20180909_0321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='user',
            new_name='author',
        ),
    ]
