# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-09 01:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0020_auto_20180909_0334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='modified_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='редактор'),
        ),
    ]
