# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-09 11:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0023_auto_20180909_0405'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detail',
            old_name='title',
            new_name='title_section',
        ),
    ]
