# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-09 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0024_auto_20180909_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='file_to',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='файл'),
        ),
    ]
