# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-09 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0025_auto_20180909_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='file_to',
            field=models.FileField(blank=True, default='', upload_to='wiki/article', verbose_name='файл'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='html_content',
            field=models.TextField(verbose_name='html'),
        ),
    ]
