# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-11 23:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0026_auto_20180909_1818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='markdown_content',
        ),
        migrations.AlterField(
            model_name='detail',
            name='html_content',
            field=models.TextField(verbose_name=''),
        ),
    ]
