# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-13 13:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0027_auto_20180912_0209'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['category'], 'verbose_name': 'статью', 'verbose_name_plural': 'статьи'},
        ),
        migrations.RemoveField(
            model_name='article',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='article',
            name='modified_by',
        ),
    ]
