# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-13 13:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0028_auto_20180913_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='pattern',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='wiki.Group', verbose_name='шаблон'),
            preserve_default=False,
        ),
    ]
