# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-13 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0031_auto_20180913_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='description',
            field=models.TextField(blank=True, verbose_name='примечание'),
        ),
    ]
